# The URL the site will be built for
base_url = "https://wasabipesto.com"
compile_sass = false
build_search_index = false

[markdown]
highlight_code = false

[extra]
# Put all your custom variables here
